AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  passmarket-puppeteer

  Sample SAM Template for passmarket-puppeteer
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PuppeteerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Layers:
        - arn:aws:lambda:ap-northeast-1:764866452798:layer:chrome-aws-lambda:48


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
   PuppeteerFunction:
    Description: "Puppeteer Lambda Function ARN"
    Value: !GetAtt PuppeteerFunction.Arn
   
   PuppeteerFunctionIamRole:
    Description: "Implicit IAM Role created for Puppeteer function"
    Value: !GetAtt PuppeteerFunctionRole.Arn