name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行される

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用する環境（今回はUbuntu）

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # コードをチェックアウト

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1  # AWSの認証情報を設定
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secretsに保存したAWSアクセスキーID
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # GitHub Secretsに保存したAWSシークレットアクセスキー
          region: ap-northeast-1  # AWSリージョン

      - name: Package Lambda function
        run: |
          zip -r my-lambda-function.zip .  # Lambda関数のコードをzipでパッケージ化

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://my-lambda-function.zip  # AWS Lambdaにデプロイ
